### ISSUE TITLE
Shield amounts incorrect for AST Nocturnal Sect

### ISSUE THREAD

**Issue by Tauri867** [ravahn/FFXIV_ACT_Plugin#60]
Currently ACT seems to be reading Nocturnal Field amounts as being 100% of the amount healed by aspected spells. It should be 170% for Aspected Benefic and 150% for Aspected Helios. (65% for Benefic and 100% for Helios in PvP, though I don't know if it's possible for ACT to differentiate that.)

**Comment by echoism7** [comment]
I've also noticed this.  Even before 3.4, nocturnal field had a bonus applied to it that wasn't updated.

**Comment by echoism7** [comment]
noticed that this is fixed in the latest version.  ty so much.

**Comment by Kayahni** [comment]
Sorry to revive this, but AST Noctural Field should now be 250% of the amount healed by Aspected Benefic, and it's still showing as 170%.  (Nocturnal Field from Aspected Helios is fine--it's still 150%.)

**Comment by ravahn** [comment]
This is late, but I did a pass on fixing damage shields, and this specific one was updated for FFXIV 5.0 expansion changes.
